name: FluxityFinance
on:
  push:
    branches:
      - 'master'
jobs:
  Build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          docker build -t fluxity-finance:latest .

  Execute:
    name: Execute
    runs-on: self-hosted
    needs: ['Build']
    steps:
      - name: Execution
        run: |
          docker-compose down
          docker-compose up -d

  Cleanup:
    name: Cleanup
    runs-on: self-hosted
    needs: ['Build', 'Execute']
    steps:
      - name: CleanImages
        run: |
          docker container prune -f
          docker image prune -af
